import classNames from 'classnames';
import type { Metadata } from 'next';
import { AvailableForHire } from '../../core/AvailableForHire';
import { HelloWorld } from '../../core/HelloWorld';
import { TextAnimateMask } from '../../core/TextAnimateMask';
import { Container } from '../Container';
import styles from './Footer.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function Footer({}) {
  return (
    <footer className={styles.footer}>
      <Container className={styles.footerContainer}>
        <div className={styles.footerGrid}>
          <div className={styles.column}>
            <HelloWorld />
          </div>

          <nav className={classNames(styles.column, styles.columnOffset)}>
            <AvailableForHire />
            <p>
              <TextAnimateMask inputRange={[0, 0.25]}>
                Schedule a quick 30min chat to discuss details about your
                project and discover what services I can offer.
              </TextAnimateMask>
            </p>
          </nav>
        </div>

        <div className={classNames(styles.footerGrid, styles.footerMeta)}>
          <div className={styles.column}>
            <span>© {new Date().getFullYear()} Sam Wyness</span>
          </div>

          <div className={classNames(styles.column, styles.columnOffset)}>
            <ul className={styles.socialLinks}>
              <li>
                <a
                  href="https://github.com/samwyness"
                  target="_blank"
                  referrerPolicy="no-referrer">
                  GitHub
                </a>
              </li>
              <li>
                <a
                  href="https://linkedin.com/in/samwyness22"
                  target="_blank"
                  referrerPolicy="no-referrer">
                  LinkedIn
                </a>
              </li>
            </ul>
          </div>
        </div>
      </Container>
    </footer>
  );
}
