import type { Metadata } from 'next';
import { AvailableForHire } from '../../core/AvailableForHire';
import { Container } from '../Container';
import { Row } from '../Row';
import styles from './Header.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function Header({}) {
  return (
    <header className={styles.header}>
      <Container>
        <Row className={styles.row}>
          <div className={styles.brand}>
            <a href="/">
              <span>
                Software Engineer &
                <br />
                <i>Creative Developer</i>
              </span>
            </a>
          </div>
          <span className={styles.scrollDown}>( SCROLL DOWN )</span>
          <AvailableForHire />
        </Row>
      </Container>
    </header>
  );
}
