import type { Metadata } from 'next';
import { AvailableForHire } from '../../AvailableForHire';
import styles from './Header.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function Header({}) {
  return (
    <header className={styles.header}>
      <div className="container">
        <div className="row">
          <span className={styles.title}>
            <code>Software Engineer &</code>
            <br />
            <strong>Creative Developer</strong>
          </span>
          <AvailableForHire />
        </div>
      </div>
    </header>
  );
}
